# Generated by Django 5.0.6 on 2024-12-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_type", models.CharField(default="00", max_length=2)),
                ("random_seed", models.IntegerField(default=0)),
                ("num_of_tries", models.IntegerField(default=1000000)),
                ("num_of_batch_jobs", models.IntegerField(default=1)),
                ("best_distance", models.CharField(default="NA", max_length=255)),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("stopped", "Stopped"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("job_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="JobStatus",
        ),
    ]
